<?php

return [
    // Ristorante 1
    [
        'restaurant_id' => 1,
        'name' => 'Mario Rossi',
        'email' => 'mario@example.com',
        'address' => 'Via Roma 1',
        'phone_num' => '+39123456789',
        'total' => 50,
        'status' => 'In preparazione',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Luigi Verdi',
        'email' => 'luigi@example.com',
        'address' => 'Via Garibaldi 2',
        'phone_num' => '+39111222333',
        'total' => 75,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Giuseppe Esposito',
        'email' => 'giuseppe@example.com',
        'address' => 'Piazza San Carlo 4',
        'phone_num' => '+39666777888',
        'total' => 45,
        'status' => 'Consegnato',
    ],

    // Ristorante 2
    [
        'restaurant_id' => 2,
        'name' => 'Francesco Ferrari',
        'email' => 'francesco@example.com',
        'address' => 'Via Milano 10',
        'phone_num' => '+39123456788',
        'total' => 60,
        'status' => 'In preparazione',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Laura Moretti',
        'email' => 'laura@example.com',
        'address' => 'Via Torino 11',
        'phone_num' => '+39111222335',
        'total' => 65,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Marco Bianchi',
        'email' => 'marco@example.com',
        'address' => 'Corso Umberto 12',
        'phone_num' => '+39444555662',
        'total' => 70,
        'status' => 'In transito',
    ],

    // Ristorante 3
    [
        'restaurant_id' => 3,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 4
    [
        'restaurant_id' => 4,
        'name' => 'Giovanna Bianchi',
        'email' => 'giovanna@example.com',
        'address' => 'Corso Vittorio Emanuele 3',
        'phone_num' => '+39444555666',
        'total' => 60,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Antonia Russo',
        'email' => 'antonia@example.com',
        'address' => 'Via Dante 5',
        'phone_num' => '+39999999999',
        'total' => 55,
        'status' => 'In preparazione',
    ],

    // Ristorante 5
    [
        'restaurant_id' => 5,
        'name' => 'Denise Bianchi',
        'email' => 'giovanna@example.com',
        'address' => 'Corso Vittorio Emanuele 3',
        'phone_num' => '+39444555666',
        'total' => 56,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 5,
        'name' => 'Nino Frassica',
        'email' => 'ninofrassica@example.com',
        'address' => 'Via Dante 5',
        'phone_num' => '+39999999999',
        'total' => 48,
        'status' => 'In preparazione',
    ],
    // Ristorante 6
    [
        'restaurant_id' => 6,
        'name' => 'Ugo Bianchi',
        'email' => 'ugo@example.com',
        'address' => 'Corso Vittorio Emanuele 3',
        'phone_num' => '+39444555666',
        'total' => 20,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Filippo Russo',
        'email' => 'filipporusso@example.com',
        'address' => 'Via Dante 5',
        'phone_num' => '+39999999999',
        'total' => 50,
        'status' => 'In preparazione',
    ],
    // Ristorante 7
    [
        'restaurant_id' => 7,
        'name' => 'Caterina Bianchi',
        'email' => 'caterinabianchi@example.com',
        'address' => 'Corso Vittorio Emanuele 3',
        'phone_num' => '+39444555666',
        'total' => 120,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Alessio Russo',
        'email' => 'alessiorusso@example.com',
        'address' => 'Via Dante 5',
        'phone_num' => '+39999999999',
        'total' => 27,
        'status' => 'In preparazione',
    ],

    // Ristorante 8
    [
        'restaurant_id' => 8,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 8,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 8,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 9
    [
        'restaurant_id' => 9,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 10
    [
        'restaurant_id' => 10,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 11
    [
        'restaurant_id' => 11,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 12
    [
        'restaurant_id' => 12,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 13
    [
        'restaurant_id' => 13,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 14
    [
        'restaurant_id' => 14,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 14,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 14,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],

    // Ristorante 3
    [
        'restaurant_id' => 15,
        'name' => 'Giovanni Moretti',
        'email' => 'giovanni@example.com',
        'address' => 'Via Garibaldi 21',
        'phone_num' => '+39111222338',
        'total' => 80,
        'status' => 'Consegnato',
    ],
    [
        'restaurant_id' => 15,
        'name' => 'Sara Bianchi',
        'email' => 'sara@example.com',
        'address' => 'Corso Vittorio Emanuele 22',
        'phone_num' => '+39444555669',
        'total' => 90,
        'status' => 'In transito',
    ],
    [
        'restaurant_id' => 15,
        'name' => 'Elena Russo',
        'email' => 'elena@example.com',
        'address' => 'Via Milano 24',
        'phone_num' => '+39999999992',
        'total' => 80,
        'status' => 'In preparazione',
    ],
    

    // Continua per gli altri ristoranti...
];