<?php 

return [
    [
        'user_id' => 1,
        'name' => 'Da Alessio',
        'address' => 'Piazza Roma, 12 - Roma - 00023',
        'img' => 'https://media-assets.lacucinaitaliana.it/photos/61fb0393f9bff304ce3ec288/16:9/w_2560%2Cc_limit/Il-meglio-del-lago-di-Orta.jpg',
    ],
    [   'user_id' => 2,
        'name' => 'Pizza e Core',
        'address' => 'Via Vivaldi, 141 - Napoli - 02032',
        'img' => 'https://www.courmayeurmontblanc.it/wp-content/uploads/2022/03/ristoranti-e-chalet-a-courmayeur5522.jpeg',
    ],
    [   'user_id' => 3,
        'name' => 'Romagna mia',
        'address' => 'Vicolo Terenzio, 6 - Firenze - 00012',
        'img' => 'https://www.bresciatoday.it/~media/horizontal-hi/38294270872571/la-sosta-brescia-2.jpg',
    ],
    [   'user_id' => 4,
        'name' => 'Mc Donald',
        'address' => 'Piazza Stesicoro, 100 - Catania - 95121',
        'img' => 'https://live.staticflickr.com/7250/7620712644_46832c2292_b.jpg',
    ],
    [   'user_id' => 5,
        'name' => 'Bakery and Dream',
        'address' => 'Via dei Sogni, 20 - Melegnano - 00201',
        'img' => 'https://citynews-veneziatoday.stgy.ovh/~media/horizontal-mid/48727478573673/pasticceria-angelica-mestre.jpg',
    ],
    [   'user_id' => 6,
        'name' => 'Pizzium',
        'address' => 'Via Augusto Anfossi, 1, 20135 Milano MI',
        'img' => 'https://tse3.mm.bing.net/th?id=OIP.glM50K-qtE9toLAJmOtvVwHaFj&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 7,
        'name' => 'Bentoteca',
        'address' => 'Via S. Calocero, 3, 20123 Milano MI',
        'img' => 'https://tse1.mm.bing.net/th?id=OIP.VcBArcvmUhgPZ8C-bLswkwHaJQ&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 8,
        'name' => 'Pasticceria Gelsomina',
        'address' => 'Via Carlo Tenca, 5, 20124 Milano MI',
        'img' => 'https://tse1.mm.bing.net/th?id=OIP.ozocCckscvGYnzF3kqIEKAHaE7&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 9,
        'name' => 'Burger King',
        'address' => 'Piazza Sant Eustorgio 2, 20122 Milano MI',
        'img' => 'https://www.cataniatoday.it/~media/horizontal-hi/5113389762073/1556898-burger-king-offre-recompense-femmes.jpeg',
    ],
    [   'user_id' => 10,
        'name' => 'Takumi',
        'address' => 'Via Luigi Canonica 63, 20154 Milano MI',
        'img' => 'https://tse4.mm.bing.net/th?id=OIP.RRLJXqxSGSx3xiQuh_nmFQAAAA&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 11,
        'name' => 'Ginmi',
        'address' => 'Via Giovanni Paisiello, 7, 20131 Milano MI',
        'img' => 'https://tse4.mm.bing.net/th?id=OIP.wsfjo9K1P27sBBoPL4JFQAHaGN&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 12,
        'name' => 'Lievità',
        'address' => 'Via Carlo Ravizza, 11, 20149 Milano MI',
        'img' => 'https://tse2.mm.bing.net/th?id=OIP.BbJw6yruJK_hvHAvgn4WjAHaEl&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 13,
        'name' => 'Ishi Fusion',
        'address' => 'Corso di Porta Ticinese, 96, 20123 Milano MI',
        'img' => 'https://tse4.mm.bing.net/th?id=OIP.q837ndwi7RfNgCDZEdmQnwHaFj&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 14,
        'name' => 'Five Guys',
        'address' => 'Corso Vittorio Emanuele II, 37, 20122 Milano MI',
        'img' => 'https://tse3.mm.bing.net/th?id=OIP.srFIaAE5KwnRCYx-xT2a5QHaEb&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 15,
        'name' => 'Pan',
        'address' => 'Via Leopoldo Cicognara, 19, 20129 Milano MI',
        'img' => 'https://tse3.mm.bing.net/th?id=OIP.bItIczh7uWbJM-IOOHwGSQHaEc&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 16,
        'name' => 'tanta roba',
        'address' => 'Via ponzio pilato, 29, 20129 Molise MO',
        'img' => 'https://img.restaurantguru.com/r1d4-Ristorante-Pizzeria-Peccati-Di-Gola-2-burger.jpg',
    ],
    [   'user_id' => 17,
        'name' => 'Osterietta',
        'address' => 'Via XXV Aprile n° 62, San Pietro Cusico, 20080 - Zibido San Giacomo, Lombardia, Italia',
        'img' => 'https://fest.ro/files/places/14/image_1445_1_preview.jpg',
    ],
    [   'user_id' => 18,
        'name' => 'Hosteria della Pignatta',
        'address' => 'Largo Loriga 5, 20082 - Binasco',
        'img' => 'https://www.hosteriadellapignatta.com/wp-content/uploads/2020/10/ingresso_pignatta-1-1500x630.jpg',
    ],
    [   'user_id' => 19,
        'name' => 'La Grancia',
        'address' => 'Corte de’ Cistercensi, 20081 - Morimondo',
        'img' => 'https://media-cdn.tripadvisor.com/media/photo-w/0f/3e/78/e7/esterno.jpg',
    ],
    [   'user_id' => 20,
        'name' => 'L’Uva E La Volpe',
        'address' => 'Via XXV Aprile n° 62, San Pietro Cusico, 20080 - Zibido San Giacomo, Lombardia, Italia',
        'img' => 'https://tse2.mm.bing.net/th?id=OIP.MFGDAzKFYoc6JvEyovpnKQHaFj&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 21,
        'name' => 'Gazebo',
        'address' => 'Indirizzo: Via Filippo Binaschi 4, 20082 - Binasco, Lombardia, Italia',
        'img' => 'https://tse4.mm.bing.net/th?id=OIP.YZMfHx5WzZ-ghWTQAk24SAHaFj&pid=Api&P=0&h=180',
    ],
    [   'user_id' => 22,
        'name' => 'New Friday',
        'address' => 'Indirizzo: Viale Monza 142, 20127 - Milano',
        'img' => 'https://tse2.mm.bing.net/th?id=OIP.Rltmt7uVVYZWiTf7qum3BgHaEK&pid=Api&P=0&h=180',
    ],
]







?>